# -*- coding: utf-8 -*-
"""FeatureEngineering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qip2bM0VwfiShAKSFQ4Ce3AS1iJyPSw
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
df1 = pd.read_csv('processed_data.csv')
df1.head()

df1['TenureInDays'] = df1['Subscription_Length_Months'] * 30  

df1['TotalMonthlyCost'] = df1['Monthly_Bill'] * df1['Subscription_Length_Months']

df1['UsageToCostRatio'] = df1['Total_Usage_GB'] / df1['TotalMonthlyCost']


location_columns = [col for col in df1.columns if col.startswith('Location_')]

location_churn_rates = df1.groupby(location_columns)['Churn'].mean().reset_index()
location_churn_rates.rename(columns={'Churn': 'ChurnRateByLocation'}, inplace=True)

df2 = df1.merge(location_churn_rates, on=location_columns, how='left')

columns_to_scale = ['Age', 'TenureInDays', 'Monthly_Bill', 'Total_Usage_GB', 'TotalMonthlyCost', 'UsageToCostRatio']

scaler = MinMaxScaler()

df2[columns_to_scale] = scaler.fit_transform(df2[columns_to_scale])

print(df2)

df2.to_csv('featureEngineered_data.csv', index=False)